import 'package:flutter/material.dart';

Color white = const Color(0xFFFFFFFF);
Color backgroud = Color(0xffF8F9FF);
Color black =  Colors.black;
Color appBarColor = Color(0xffFAFAF9);
Color primary =  Color(0xff064E3B);
Color pink = const Color(0xffF9CFD4);
Color red = const Color(0xffDF5050);
Color yellow = const Color(0xffFFE90B);
Color gold = const Color(0xffEFB71D);
Color skyBlue = const Color(0xffACDCF5);
Color blue = const Color(0xff1EB8FF);
Color lightBlue = const Color(0xfff4f8ff);
Color blue2 = const Color(0xff181A1F);
Color blue3 = const Color(0xff1168A7);
Color blue4 = const Color(0xff2f88ff);
Color navyBlue = const Color(0xFF1E3269);
Color lightGrey = Color(0xffdadada);
Color otherGrey = Color(0xffF9F9F9);
const lightAppColor = Color(0xee009eea);
const appdark = Color(0xff1E1E1E);
const appPurple = Color(0xFF775CB0);
Color greenAccent = Color(0xffD1FAE5);
Color grey = const Color(0xFF9A9A9A);
Color cautionHome = const Color(0xFFF9CFD4);
Color backgroundBarrier = const Color(0xFFA6B4BE);
